# Training configuration
notes: "nwm_cdit_default"
run_name: ${now:%Y%m%d_%H%M%S}_${training.notes}
results_dir: logs/nwm_training
batch_size: 16
num_workers: 8
grad_clip_val: 10.0

# Checkpoint
from_checkpoint: null  # Path to checkpoint for resuming training

# Optimizer
optimizer:
  _target_: torch.optim.AdamW
  lr: 8e-5
  weight_decay: 0.0

# WandB Logging
wandb_enabled: true
wandb_project: "nwm-training"
wandb_notes: ${training.run_name}
wandb_tags: [] 