# @package _global_
model:
  tokenizer:
    compact_tokenizer:
      diffusion:
        _target_: diffusion.disc_diffusion.DiscreteDiffusionWithCFG
        mask_token_id: ${model.tokenizer.base_tokenizer.n_embed}
        num_timesteps: 1
        schedule_type: "all"
        temperature: 1.0
        output_key: "decoder_2d_logits"
        cfg_prob: 0.1