# @package _global_
model:
  tokenizer:
    _target_: tokenizer_wrapper.FlexTokenWrapper
    model_path: EPFL-VILAB/flextok_d12_d12_in1k
    num_tokens: 16
    codebook_size: 64000
    normalize_mean: [0.5, 0.5, 0.5]
    normalize_std: [0.5, 0.5, 0.5]

dataset:
  image_size: 224
  mean: [0.5, 0.5, 0.5]
  std: [0.5, 0.5, 0.5]